package shared.configLoader;

import org.json.simple.JSONObject;
import static shared.constants.ExceptionConstants.*;


public class LanguageLoader {

    public static void loadConfig(JSONObject jsonLanguage) {
        GAME_NOT_IN_AVAILABLE_LIST = (String) jsonLanguage.get("GAME_NOT_IN_AVAILABLE_LIST");
        DICEBAG_WRONG_NUMBER = (String) jsonLanguage.get("DICEBAG_WRONG_NUMBER");
        CANNOT_CREATE_PLAYER = (String) jsonLanguage.get("CANNOT_CREATE_PLAYER");
        INVALID_MULTIPLAYER_GAME_PLAYERS_P1 = (String) jsonLanguage.get("INVALID_MULTIPLAYER_GAME_PLAYERS_P1");
        INVALID_MULTIPLAYER_GAME_PLAYERS_P2 = (String) jsonLanguage.get("INVALID_MULTIPLAYER_GAME_PLAYERS_P2");
        INVALID_MULTIPLAYER_GAME_PLAYERS_P3 = (String) jsonLanguage.get("INVALID_MULTIPLAYER_GAME_PLAYERS_P3");
        INVALID_MULTIPLAYER_GAME_PLAYERS_P4 = (String) jsonLanguage.get("INVALID_MULTIPLAYER_GAME_PLAYERS_P4");
        INVALID_SINGLEPLAYER_GAME_PLAYERS_P1 = (String) jsonLanguage.get("INVALID_SINGLEPLAYER_GAME_PLAYERS_P1");
        INVALID_SINGLEPLAYER_GAME_PLAYERS_P2 = (String) jsonLanguage.get("INVALID_SINGLEPLAYER_GAME_PLAYERS_P2");
        INVALID_NUM_OF_PLAYERS = (String) jsonLanguage.get("INVALID_NUM_OF_PLAYERS");
        MAX_PLAYER_EXCEEDED_P1 = (String) jsonLanguage.get("MAX_PLAYER_EXCEEDED_P1");
        MAX_PLAYER_EXCEEDED_P2 = (String) jsonLanguage.get("MAX_PLAYER_EXCEEDED_P2");
        MAX_PLAYER_EXCEEDED_P3 = (String) jsonLanguage.get("MAX_PLAYER_EXCEEDED_P3");
        NOT_ENOUGH_PLAYERS_P1 = (String) jsonLanguage.get("NOT_ENOUGH_PLAYERS_P1");
        NOT_ENOUGH_PLAYERS_P2 = (String) jsonLanguage.get("NOT_ENOUGH_PLAYERS_P2");
        NOT_ENOUGH_PLAYERS_P3 = (String) jsonLanguage.get("NOT_ENOUGH_PLAYERS_P3");
        NOT_YOUR_WPC_P1 = (String) jsonLanguage.get("NOT_YOUR_WPC_P1");
        NOT_YOUR_WPC_P2 = (String) jsonLanguage.get("NOT_YOUR_WPC_P2");
        USER_ALREADY_IN_GAME = (String) jsonLanguage.get("USER_ALREADY_IN_GAME");
        USER_NOT_IN_GAME = (String) jsonLanguage.get("USER_NOT_IN_GAME");
        CANNOT_ADD_PLAYER_IN_DB = (String) jsonLanguage.get("CANNOT_ADD_PLAYER_IN_DB");
        CANNOT_CANCEL_ACTION_0 = (String) jsonLanguage.get("CANNOT_CANCEL_ACTION_0");
        CANNOT_CANCEL_ACTION_1_P1 = (String) jsonLanguage.get("CANNOT_CANCEL_ACTION_1_P1");
        CANNOT_CANCEL_ACTION_1_P2 = (String) jsonLanguage.get("CANNOT_CANCEL_ACTION_1_P2");
        CANNOT_CANCEL_ACTION_1_P3 = (String) jsonLanguage.get("CANNOT_CANCEL_ACTION_1_P3");
        CANNOT_CANCEL_ACTION_2_P1 = (String) jsonLanguage.get("CANNOT_CANCEL_ACTION_2_P1");
        CANNOT_CANCEL_ACTION_2_P2 = (String) jsonLanguage.get("CANNOT_CANCEL_ACTION_2_P2");
        CANNOT_CANCEL_ACTION_3_P1 = (String) jsonLanguage.get("CANNOT_CANCEL_ACTION_3_P1");
        CANNOT_CANCEL_ACTION_3_P2 = (String) jsonLanguage.get("CANNOT_CANCEL_ACTION_3_P2");
        CANNOT_CLOSE_OLD_CONNECTION_0 = (String) jsonLanguage.get("CANNOT_CLOSE_OLD_CONNECTION_0");
        CANNOT_CLOSE_OLD_CONNECTION_1 = (String) jsonLanguage.get("CANNOT_CLOSE_OLD_CONNECTION_1");
        CANNOT_CLOSE_OLD_CONNECTION_2 = (String) jsonLanguage.get("CANNOT_CLOSE_OLD_CONNECTION_2");
        CANNOT_FIND_GAME_FOR_USER = (String) jsonLanguage.get("CANNOT_FIND_GAME_FOR_USER");
        CANNOT_FIND_PLAYER_IN_DB = (String) jsonLanguage.get("CANNOT_FIND_PLAYER_IN_DB");
        CANNOT_FIND_USER_IN_DB_P1 = (String) jsonLanguage.get("CANNOT_FIND_USER_IN_DB_P1");
        CANNOT_FIND_USER_IN_DB_P2 = (String) jsonLanguage.get("CANNOT_FIND_USER_IN_DB_P2");
        CANNOT_INTERRUPT_TOOLCARD_P1 = (String) jsonLanguage.get("CANNOT_INTERRUPT_TOOLCARD_P1");
        CANNOT_INTERRUPT_TOOLCARD_P2 = (String) jsonLanguage.get("CANNOT_INTERRUPT_TOOLCARD_P2");
        CANNOT_LOGIN_USER_03_P1 = (String) jsonLanguage.get("CANNOT_LOGIN_USER_03_P1");
        CANNOT_LOGIN_USER_0_P2 = (String) jsonLanguage.get("CANNOT_LOGIN_USER_0_P2");
        CANNOT_LOGIN_USER_1_P1 = (String) jsonLanguage.get("CANNOT_LOGIN_USER_1_P1");
        CANNOT_LOGIN_USER_1_P2 = (String) jsonLanguage.get("CANNOT_LOGIN_USER_1_P2");
        CANNOT_LOGIN_USER_2_P1 = (String) jsonLanguage.get("CANNOT_LOGIN_USER_2_P1");
        CANNOT_LOGIN_USER_2_P2 = (String) jsonLanguage.get("CANNOT_LOGIN_USER_2_P2");
        CANNOT_LOGIN_USER_3_P2 = (String) jsonLanguage.get("CANNOT_LOGIN_USER_3_P2");
        CANNOT_LOGIN_USER_4 = (String) jsonLanguage.get("CANNOT_LOGIN_USER_4");
        CANNOT_PERFORM_THIS_MOVE_NAME_1 = (String) jsonLanguage.get("CANNOT_PERFORM_THIS_MOVE_NAME_1");
        CANNOT_PERFORM_THIS_MOVE_NAME_2 = (String) jsonLanguage.get("CANNOT_PERFORM_THIS_MOVE_NAME_2");
        CANNOT_PERFORM_THIS_MOVE_IMPOSSIBLE = (String) jsonLanguage.get("CANNOT_PERFORM_THIS_MOVE_IMPOSSIBLE");
        CANNOT_PERFORM_THIS_MOVE_FOR_PLAYER = (String) jsonLanguage.get("CANNOT_PERFORM_THIS_MOVE_FOR_PLAYER");
        CANNOT_PERFORM_THIS_MOVE_0 = (String) jsonLanguage.get("CANNOT_PERFORM_THIS_MOVE_0");
        CANNOT_PERFORM_THIS_MOVE_1 = (String) jsonLanguage.get("CANNOT_PERFORM_THIS_MOVE_1");
        CANNOT_PERFORM_THIS_MOVE_2 = (String) jsonLanguage.get("CANNOT_PERFORM_THIS_MOVE_2");
        CANNOT_PERFORM_THIS_MOVE_3 = (String) jsonLanguage.get("CANNOT_PERFORM_THIS_MOVE_3");
        CANNOT_PICK_DICE = (String) jsonLanguage.get("CANNOT_PICK_DICE");
        CANNOT_PICK_DICE_0_P1 = (String) jsonLanguage.get("CANNOT_PICK_DICE_0_P1");
        CANNOT_PICK_DICE_0_P2 = (String) jsonLanguage.get("CANNOT_PICK_DICE_0_P2");
        CANNOT_PICK_DICE_1 = (String) jsonLanguage.get("CANNOT_PICK_DICE_1");
        CANNOT_PICK_DICE_2 = (String) jsonLanguage.get("CANNOT_PICK_DICE_2");
        CANNOT_PICK_DICE_3 = (String) jsonLanguage.get("CANNOT_PICK_DICE_3");
        CANNOT_PICK_DICE_4 = (String) jsonLanguage.get("CANNOT_PICK_DICE_4");
        CANNOT_PICK_DICE_5 = (String) jsonLanguage.get("CANNOT_PICK_DICE_5");
        CANNOT_PICK_NUMBER = (String) jsonLanguage.get("CANNOT_PICK_NUMBER");
        CANNOT_PICK_POSITION = (String) jsonLanguage.get("CANNOT_PICK_POSITION");
        CANNOT_REGISTER_USER_0_P1 = (String) jsonLanguage.get("CANNOT_REGISTER_USER_0_P1");
        CANNOT_REGISTER_USER_0_P2 = (String) jsonLanguage.get("CANNOT_REGISTER_USER_0_P2");
        CANNOT_REGISTER_USER_1_P1 = (String) jsonLanguage.get("CANNOT_REGISTER_USER_1_P1");
        CANNOT_REGISTER_USER_1_P2 = (String) jsonLanguage.get("CANNOT_REGISTER_USER_1_P2");
        CANNOT_REGISTER_USER_2_P1 = (String) jsonLanguage.get("CANNOT_REGISTER_USER_2_P1");
        CANNOT_REGISTER_USER_2_P2 = (String) jsonLanguage.get("CANNOT_REGISTER_USER_2_P2");
        CANNOT_UPDATE_STATS_P2 = (String) jsonLanguage.get("CANNOT_UPDATE_STATS_P2");
        CANNOT_PICK_TOOLCARD = (String) jsonLanguage.get("CANNOT_PICK_TOOLCARD");
        CANNOT_USE_TOOLCARD = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD");
        CANNOT_USE_TOOLCARD_0 = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD_0");
        CANNOT_USE_TOOLCARD_1 = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD_1");
        CANNOT_USE_TOOLCARD_2 = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD_2");
        CANNOT_USE_TOOLCARD_3 = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD_3");
        CANNOT_USE_TOOLCARD_45 = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD_45");
        CANNOT_USE_TOOLCARD_6 = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD_6");
        CANNOT_USE_TOOLCARD_7 = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD_7");
        CANNOT_USE_TOOLCARD_8 = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD_8");
        CANNOT_USE_TOOLCARD_DEF = (String) jsonLanguage.get("CANNOT_USE_TOOLCARD_DEF");
        DATABASE_FILE_ERROR_0 = (String) jsonLanguage.get("DATABASE_FILE_ERROR_0");
        DATABASE_FILE_ERROR_1 = (String) jsonLanguage.get("DATABASE_FILE_ERROR_1");
        NO_SOCKET_FOUND_P1 = (String) jsonLanguage.get("NO_SOCKET_FOUND_P1");
        NO_SOCKET_FOUND_P2 = (String) jsonLanguage.get("NO_SOCKET_FOUND_P2");
        NO_TOOLCARD_IN_USE = (String) jsonLanguage.get("NO_TOOLCARD_IN_USE");
        NULL_TOKEN = (String) jsonLanguage.get("NULL_TOKEN");
        PASSWORD_PARSING_ERROR = (String) jsonLanguage.get("PASSWORD_PARSING_ERROR");
        PLAYER_NOT_AUTHORIZED_P1 = (String) jsonLanguage.get("PLAYER_NOT_AUTHORIZED_P1");
        PLAYER_NOT_AUTHORIZED_P2 = (String) jsonLanguage.get("PLAYER_NOT_AUTHORIZED_P2");
        INVALID_WPC_ID = (String) jsonLanguage.get("INVALID_WPC_ID");
        NOT_EXISTING_CELL = (String) jsonLanguage.get("NOT_EXISTING_CELL");
    }
}
